/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-6.3
 * 
 * Declare the raycasterfs string.
 *
 */
#ifndef __raycasterfs_h
#define __raycasterfs_h

#include "vtkRenderingVolumeOpenGL2Module.h"

VTKRENDERINGVOLUMEOPENGL2_EXPORT extern const char *raycasterfs;

#endif /* #ifndef __raycasterfs_h */
