# CMake generated Testfile for 
# Source directory: /home/cheen/Desktop/410/VTK/Filters/Sources/Testing/Cxx
# Build directory: /home/cheen/Desktop/410/VTK-build/Filters/Sources/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkFiltersSourcesCxx-TestArcSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestArcSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestArcSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestConeSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestConeSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestConeSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestCubeSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestCubeSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestCubeSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestCylinderSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestCylinderSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestCylinderSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestDiskSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestDiskSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestDiskSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestEllipticalButtonSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestEllipticalButtonSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestEllipticalButtonSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestFrustumSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestFrustumSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestFrustumSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestGlyphSource2D "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestGlyphSource2D" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestGlyphSource2D PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestLineSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestLineSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestLineSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestMultiBlock "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestMultiBlock" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/Sources/Testing/Data/Baseline/TestMultiBlock.png")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestMultiBlock PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestOutlineCornerSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestOutlineCornerSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestOutlineCornerSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestOutlineSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestOutlineSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestOutlineSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestParametricFunctionSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestParametricFunctionSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestParametricFunctionSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestPlaneSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestPlaneSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestPlaneSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestPlatonicSolidSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestPlatonicSolidSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestPlatonicSolidSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestPointSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestPointSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestPointSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestPolyLineSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestPolyLineSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestPolyLineSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestRectangularButtonSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestRectangularButtonSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestRectangularButtonSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestRegularPolygonSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestRegularPolygonSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestRegularPolygonSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestSphereSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestSphereSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestSphereSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestSuperquadricSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestSuperquadricSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestSuperquadricSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestTessellatedBoxSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestTessellatedBoxSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestTessellatedBoxSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestTextSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestTextSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestTextSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestTexturedSphereSource "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestTexturedSphereSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestTexturedSphereSource PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersSourcesCxx-TestGlyphSource2DResolution "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersSourcesCxxTests" "TestGlyphSource2DResolution" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/Sources/Testing/Data/Baseline/TestGlyphSource2DResolution.png")
SET_TESTS_PROPERTIES(vtkFiltersSourcesCxx-TestGlyphSource2DResolution PROPERTIES  LABELS "")
