# CMake generated Testfile for 
# Source directory: /home/cheen/Desktop/410/VTK/Filters/General/Testing/Cxx
# Build directory: /home/cheen/Desktop/410/VTK-build/Filters/General/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkFiltersGeneralCxx-ArrayExtractFactoredArray "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "ArrayExtractFactoredArray" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-ArrayExtractFactoredArray PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-ArrayMatricizeArray "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "ArrayMatricizeArray" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-ArrayMatricizeArray PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-ArrayNormalizeMatrixVectors "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "ArrayNormalizeMatrixVectors" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-ArrayNormalizeMatrixVectors PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-CellTreeLocator "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "CellTreeLocator" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-CellTreeLocator PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestPassArrays "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestPassArrays" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestPassArrays PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestPassThrough "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestPassThrough" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestPassThrough PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestTessellator "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestTessellator" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestTessellator PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-expCos "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "expCos" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/expCos.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-expCos PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-BoxClipPolyData "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "BoxClipPolyData" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/BoxClipPolyData.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-BoxClipPolyData PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-BoxClipTetrahedra "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "BoxClipTetrahedra" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/BoxClipTetrahedra.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-BoxClipTetrahedra PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-BoxClipTriangulateAndInterpolate "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "BoxClipTriangulateAndInterpolate" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/BoxClipTriangulateAndInterpolate.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-BoxClipTriangulateAndInterpolate PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-BoxClipTriangulate "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "BoxClipTriangulate" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-BoxClipTriangulate PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestAppendPoints "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestAppendPoints" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestAppendPoints PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestBooleanOperationPolyDataFilter2 "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestBooleanOperationPolyDataFilter2" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestBooleanOperationPolyDataFilter2.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestBooleanOperationPolyDataFilter2 PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestBooleanOperationPolyDataFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestBooleanOperationPolyDataFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestBooleanOperationPolyDataFilter.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestBooleanOperationPolyDataFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestContourTriangulatorCutter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestContourTriangulatorCutter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestContourTriangulatorCutter.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestContourTriangulatorCutter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestContourTriangulator "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestContourTriangulator" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestContourTriangulator.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestContourTriangulator PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestContourTriangulatorMarching "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestContourTriangulatorMarching" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestContourTriangulatorMarching.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestContourTriangulatorMarching PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestDeformPointSet "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestDeformPointSet" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestDeformPointSet.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestDeformPointSet PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestDensifyPolyData "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestDensifyPolyData" "-E15" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestDensifyPolyData.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestDensifyPolyData PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestDistancePolyDataFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestDistancePolyDataFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestDistancePolyDataFilter.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestDistancePolyDataFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestGraphWeightEuclideanDistanceFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestGraphWeightEuclideanDistanceFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestGraphWeightEuclideanDistanceFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestImageDataToPointSet "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestImageDataToPointSet" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestImageDataToPointSet PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestIntersectionPolyDataFilter2 "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestIntersectionPolyDataFilter2" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestIntersectionPolyDataFilter2 PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestIntersectionPolyDataFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestIntersectionPolyDataFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestIntersectionPolyDataFilter.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestIntersectionPolyDataFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestRectilinearGridToPointSet "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestRectilinearGridToPointSet" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestRectilinearGridToPointSet PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestReflectionFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestReflectionFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestReflectionFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestTableSplitColumnComponents "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestTableSplitColumnComponents" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestTableSplitColumnComponents PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestTransformFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestTransformFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestTransformFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestTransformPolyDataFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestTransformPolyDataFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestTransformPolyDataFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestUncertaintyTubeFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestUncertaintyTubeFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestUncertaintyTubeFilter.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestUncertaintyTubeFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-UnitTestMultiThreshold "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "UnitTestMultiThreshold" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-UnitTestMultiThreshold PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestGradientAndVorticity "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestGradientAndVorticity" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestGradientAndVorticity PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestIconGlyphFilterGravity "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestIconGlyphFilterGravity" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestIconGlyphFilterGravity.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestIconGlyphFilterGravity PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestQuadraturePoints "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestQuadraturePoints" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestQuadraturePoints.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestQuadraturePoints PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersGeneralCxx-TestYoungsMaterialInterface "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersGeneralCxxTests" "TestYoungsMaterialInterface" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/General/Testing/Data/Baseline/TestYoungsMaterialInterface.png")
SET_TESTS_PROPERTIES(vtkFiltersGeneralCxx-TestYoungsMaterialInterface PROPERTIES  LABELS "" TIMEOUT "300")
