# CMake generated Testfile for 
# Source directory: /home/cheen/Desktop/410/VTK/Imaging/Core/Testing/Cxx
# Build directory: /home/cheen/Desktop/410/VTK-build/Imaging/Core/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkImagingCoreCxx-FastSplatter "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "FastSplatter" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/FastSplatter.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-FastSplatter PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImageAccumulate "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImageAccumulate" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImageAccumulate PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImageAccumulateLarge "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImageAccumulateLarge" "32")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImageAccumulateLarge PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImageAutoRange "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImageAutoRange" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/ImageAutoRange.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImageAutoRange PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImageBSplineCoefficients "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImageBSplineCoefficients" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/ImageBSplineCoefficients.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImageBSplineCoefficients PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImageHistogram "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImageHistogram" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/ImageHistogram.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImageHistogram PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImageHistogramStatistics "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImageHistogramStatistics" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImageHistogramStatistics PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImageResize "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImageResize" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/ImageResize.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImageResize PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImageResize3D "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImageResize3D" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/ImageResize3D.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImageResize3D PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImageResizeCropping "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImageResizeCropping" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/ImageResizeCropping.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImageResizeCropping PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImageWeightedSum "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImageWeightedSum" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImageWeightedSum PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-ImportExport "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "ImportExport" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-ImportExport PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-TestBSplineWarp "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "TestBSplineWarp" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/TestBSplineWarp.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-TestBSplineWarp PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-TestImageStencilDataMethods "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "TestImageStencilDataMethods" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-TestImageStencilDataMethods PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-TestStencilWithLasso "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "TestStencilWithLasso" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/TestStencilWithLasso.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-TestStencilWithLasso PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-TestStencilWithPolyDataContour "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "TestStencilWithPolyDataContour" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/TestStencilWithPolyDataContour.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-TestStencilWithPolyDataContour PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-TestStencilWithPolyDataSurface "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "TestStencilWithPolyDataSurface" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/TestStencilWithPolyDataSurface.png")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-TestStencilWithPolyDataSurface PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-TestUpdateExtentReset "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "TestUpdateExtentReset" "32" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkImagingCoreCxx-TestUpdateExtentReset PROPERTIES  LABELS "")
ADD_TEST(vtkImagingCoreCxx-AddStencilData "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "TestImageStencilData" "1" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/TestAddStencilData.png")
ADD_TEST(vtkImagingCoreCxx-SubtractStencilData "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "TestImageStencilData" "2" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/TestSubtractStencilData.png")
ADD_TEST(vtkImagingCoreCxx-ClipStencilData "/home/cheen/Desktop/410/VTK-build/bin/vtkImagingCoreCxxTests" "TestImageStencilData" "3" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Imaging/Core/Testing/Data/Baseline/TestClipStencilData.png")
