/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-6.3
 * 
 * Declare the vtkSphereMapperVS string.
 *
 */
#ifndef __vtkSphereMapperVS_h
#define __vtkSphereMapperVS_h

#include "vtkDomainsChemistryOpenGL2Module.h"

VTKDOMAINSCHEMISTRYOPENGL2_EXPORT extern const char *vtkSphereMapperVS;

#endif /* #ifndef __vtkSphereMapperVS_h */
