/* DO NOT EDIT.
 * Generated by ../../bin/vtkEncodeString-6.3
 * 
 * Declare the vtkStickMapperVS string.
 *
 */
#ifndef __vtkStickMapperVS_h
#define __vtkStickMapperVS_h

#include "vtkDomainsChemistryOpenGL2Module.h"

VTKDOMAINSCHEMISTRYOPENGL2_EXPORT extern const char *vtkStickMapperVS;

#endif /* #ifndef __vtkStickMapperVS_h */
