# CMake generated Testfile for 
# Source directory: /home/cheen/Desktop/410/VTK/Rendering/FreeType/Testing/Cxx
# Build directory: /home/cheen/Desktop/410/VTK-build/Rendering/FreeType/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkRenderingFreeTypeCxx-TestFTStringToPath "/home/cheen/Desktop/410/VTK-build/bin/vtkRenderingFreeTypeCxxTests" "TestFTStringToPath" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestFTStringToPath.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestFTStringToPath PROPERTIES  LABELS "")
ADD_TEST(vtkRenderingFreeTypeCxx-TestFreeTypeTextMapperNoMath "/home/cheen/Desktop/410/VTK-build/bin/vtkRenderingFreeTypeCxxTests" "TestFreeTypeTextMapperNoMath" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Fonts/DejaVuSans.ttf" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestFreeTypeTextMapperNoMath.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestFreeTypeTextMapperNoMath PROPERTIES  LABELS "")
ADD_TEST(vtkRenderingFreeTypeCxx-TestMathTextFreeTypeTextRendererNoMath "/home/cheen/Desktop/410/VTK-build/bin/vtkRenderingFreeTypeCxxTests" "TestMathTextFreeTypeTextRendererNoMath" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Fonts/DejaVuSans.ttf" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestMathTextFreeTypeTextRendererNoMath.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestMathTextFreeTypeTextRendererNoMath PROPERTIES  LABELS "")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActor "/home/cheen/Desktop/410/VTK-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActor" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActor.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActor PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR:" LABELS "")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActor3D "/home/cheen/Desktop/410/VTK-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActor3D" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActor3D.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActor3D PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR:" LABELS "")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActorAlphaBlending "/home/cheen/Desktop/410/VTK-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActorAlphaBlending" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActorAlphaBlending.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActorAlphaBlending PROPERTIES  LABELS "")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActorDepthPeeling "/home/cheen/Desktop/410/VTK-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActorDepthPeeling" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActorDepthPeeling.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActorDepthPeeling PROPERTIES  LABELS "")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActor3DAlphaBlending "/home/cheen/Desktop/410/VTK-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActor3DAlphaBlending" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActor3DAlphaBlending.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActor3DAlphaBlending PROPERTIES  LABELS "")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActor3DDepthPeeling "/home/cheen/Desktop/410/VTK-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActor3DDepthPeeling" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActor3DDepthPeeling.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActor3DDepthPeeling PROPERTIES  LABELS "")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextMapper "/home/cheen/Desktop/410/VTK-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextMapper" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextMapper.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextMapper PROPERTIES  LABELS "")
