# CMake generated Testfile for 
# Source directory: /home/cheen/Desktop/410/VTK/Common/DataModel/Testing/Cxx
# Build directory: /home/cheen/Desktop/410/VTK-build/Common/DataModel/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkCommonDataModelCxx-TestColor "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestColor")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestColor PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestVector "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestVector")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestVector PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestVectorOperators "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestVectorOperators")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestVectorOperators PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestAMRBox "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestAMRBox")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestAMRBox PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestBiQuadraticQuad "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestBiQuadraticQuad")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestBiQuadraticQuad PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestCompositeDataSets "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestCompositeDataSets")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestCompositeDataSets PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestComputeBoundingSphere "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestComputeBoundingSphere")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestComputeBoundingSphere PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestDataArrayDispatcher "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestDataArrayDispatcher")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestDataArrayDispatcher PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestDataObject "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestDataObject")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestDataObject PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestDispatchers "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestDispatchers")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestDispatchers PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestGenericCell "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestGenericCell")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestGenericCell PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestGraph "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestGraph")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestGraph PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestGraph2 "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestGraph2")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestGraph2 PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestGraphAttributes "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestGraphAttributes")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestGraphAttributes PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestHigherOrderCell "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestHigherOrderCell")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestHigherOrderCell PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestImageDataFindCell "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestImageDataFindCell")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestImageDataFindCell PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestImageDataInterpolation "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestImageDataInterpolation")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestImageDataInterpolation PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestImageIterator "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestImageIterator")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestImageIterator PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestInterpolationDerivs "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestInterpolationDerivs")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestInterpolationDerivs PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestInterpolationFunctions "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestInterpolationFunctions")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestInterpolationFunctions PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestPath "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestPath")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestPath PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestPentagonalPrism "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestPentagonalPrism")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestPentagonalPrism PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestPixelExtent "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestPixelExtent")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestPixelExtent PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestPointLocators "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestPointLocators")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestPointLocators PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestPolyDataRemoveCell "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestPolyDataRemoveCell")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestPolyDataRemoveCell PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestPolygon "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestPolygon")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestPolygon PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestPolyhedron0 "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestPolyhedron0")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestPolyhedron0 PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestPolyhedron1 "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestPolyhedron1")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestPolyhedron1 PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestQuadraticPolygon "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestQuadraticPolygon")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestQuadraticPolygon PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestSelectionSubtract "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestSelectionSubtract")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestSelectionSubtract PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestTable "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestTable")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestTable PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestTreeBFSIterator "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestTreeBFSIterator")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestTreeBFSIterator PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestTreeDFSIterator "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestTreeDFSIterator")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestTreeDFSIterator PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestTriangle "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestTriangle")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestTriangle PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-otherCellArray "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "otherCellArray")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-otherCellArray PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-otherCellBoundaries "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "otherCellBoundaries")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-otherCellBoundaries PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-otherCellPosition "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "otherCellPosition")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-otherCellPosition PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-otherCellTypes "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "otherCellTypes")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-otherCellTypes PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-otherColorTransferFunction "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "otherColorTransferFunction")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-otherColorTransferFunction PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-otherEmptyCell "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "otherEmptyCell")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-otherEmptyCell PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-otherFieldData "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "otherFieldData")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-otherFieldData PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-otherRectilinearGrid "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "otherRectilinearGrid")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-otherRectilinearGrid PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-otherStructuredGrid "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "otherStructuredGrid")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-otherStructuredGrid PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-quadCellConsistency "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "quadCellConsistency")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-quadCellConsistency PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-quadraticEvaluation "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "quadraticEvaluation")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-quadraticEvaluation PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestBoundingBox "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestBoundingBox")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestBoundingBox PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestPlane "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestPlane")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestPlane PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestStructuredData "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestStructuredData")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestStructuredData PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestDataObjectTypes "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestDataObjectTypes")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestDataObjectTypes PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestPolyDataRemoveDeletedCells "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestPolyDataRemoveDeletedCells")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestPolyDataRemoveDeletedCells PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-UnitTestCells "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "UnitTestCells")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-UnitTestCells PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-UnitTestImplicitDataSet "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "UnitTestImplicitDataSet")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-UnitTestImplicitDataSet PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-UnitTestImplicitVolume "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "UnitTestImplicitVolume")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-UnitTestImplicitVolume PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-UnitTestPlanesIntersection "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "UnitTestPlanesIntersection")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-UnitTestPlanesIntersection PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-quadraticIntersection "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "quadraticIntersection" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Common/DataModel/Testing/Data/Baseline/quadraticIntersection.png")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-quadraticIntersection PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestCellIterators "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestCellIterators" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestCellIterators PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestCellLocator "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestCellLocator" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Common/DataModel/Testing/Data/Baseline/TestCellLocator.png")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestCellLocator PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestMeanValueCoordinatesInterpolation1 "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestMeanValueCoordinatesInterpolation1" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Common/DataModel/Testing/Data/Baseline/TestMeanValueCoordinatesInterpolation1.png")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestMeanValueCoordinatesInterpolation1 PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestMeanValueCoordinatesInterpolation2 "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestMeanValueCoordinatesInterpolation2" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Common/DataModel/Testing/Data/Baseline/TestMeanValueCoordinatesInterpolation2.png")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestMeanValueCoordinatesInterpolation2 PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestSmoothErrorMetric "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestSmoothErrorMetric" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Common/DataModel/Testing/Data/Baseline/TestSmoothErrorMetric.png")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestSmoothErrorMetric PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestQuadraticPolygonFilters "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestQuadraticPolygonFilters" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Common/DataModel/Testing/Data/Baseline/TestQuadraticPolygonFilters.png")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestQuadraticPolygonFilters PROPERTIES  LABELS "")
ADD_TEST(vtkCommonDataModelCxx-TestKdTreeRepresentation "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonDataModelCxxTests" "TestKdTreeRepresentation" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Common/DataModel/Testing/Data/Baseline/TestKdTreeRepresentation.png")
SET_TESTS_PROPERTIES(vtkCommonDataModelCxx-TestKdTreeRepresentation PROPERTIES  LABELS "")
