# CMake generated Testfile for 
# Source directory: /home/cheen/Desktop/410/VTK/Common/Core/Testing/Cxx
# Build directory: /home/cheen/Desktop/410/VTK-build/Common/Core/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkCommonCoreCxx-UnitTestMath "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "UnitTestMath")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-UnitTestMath PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestAngularPeriodicDataArray "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestAngularPeriodicDataArray")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestAngularPeriodicDataArray PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayAPI "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayAPI")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayAPI PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayAPIConvenience "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayAPIConvenience")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayAPIConvenience PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayAPIDense "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayAPIDense")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayAPIDense PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayAPISparse "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayAPISparse")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayAPISparse PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayBool "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayBool")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayBool PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestAtomic "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestAtomic")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestAtomic PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestScalarsToColors "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestScalarsToColors")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestScalarsToColors PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayExtents "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayExtents")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayExtents PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayInterpolationDense "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayInterpolationDense")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayInterpolationDense PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayLookup "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayLookup")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayLookup PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayNullValues "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayNullValues")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayNullValues PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArraySize "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArraySize")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArraySize PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayUniqueValueDetection "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayUniqueValueDetection")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayUniqueValueDetection PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayUserTypes "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayUserTypes")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayUserTypes PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestArrayVariants "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestArrayVariants")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestArrayVariants PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestCollection "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestCollection")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestCollection PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestConditionVariable "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestConditionVariable")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestConditionVariable PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestDataArray "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestDataArray")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestDataArray PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestDataArrayAPI "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestDataArrayAPI")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestDataArrayAPI PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestDataArrayComponentNames "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestDataArrayComponentNames")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestDataArrayComponentNames PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestDataArrayIterators "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestDataArrayIterators")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestDataArrayIterators PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestGarbageCollector "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestGarbageCollector")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestGarbageCollector PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestLookupTable "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestLookupTable")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestLookupTable PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestLookupTableThreaded "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestLookupTableThreaded")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestLookupTableThreaded PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestMath "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestMath")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestMath PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestMinimalStandardRandomSequence "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestMinimalStandardRandomSequence")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestMinimalStandardRandomSequence PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestNew "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestNew")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestNew PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestObjectFactory "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestObjectFactory")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestObjectFactory PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestObservers "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestObservers")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestObservers PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestObserversPerformance "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestObserversPerformance")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestObserversPerformance PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestOStreamWrapper "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestOStreamWrapper")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestOStreamWrapper PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestSMP "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestSMP")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestSMP PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestSmartPointer "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestSmartPointer")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestSmartPointer PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestSortDataArray "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestSortDataArray")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestSortDataArray PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestSparseArrayValidation "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestSparseArrayValidation")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestSparseArrayValidation PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestSystemInformation "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestSystemInformation" "/home/cheen/Desktop/410/VTK-build")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestSystemInformation PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestTemplateMacro "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestTemplateMacro")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestTemplateMacro PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestTimePointUtility "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestTimePointUtility")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestTimePointUtility PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestUnicodeStringAPI "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestUnicodeStringAPI")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestUnicodeStringAPI PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestUnicodeStringArrayAPI "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestUnicodeStringArrayAPI")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestUnicodeStringArrayAPI PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestVariant "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestVariant")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestVariant PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestVariantComparison "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestVariantComparison")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestVariantComparison PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestWeakPointer "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestWeakPointer")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestWeakPointer PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-TestXMLFileOutputWindow "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "TestXMLFileOutputWindow" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary/XMLFileOutputWindow.txt")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-TestXMLFileOutputWindow PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-UnitTestInformationKeys "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "UnitTestInformationKeys")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-UnitTestInformationKeys PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-otherArrays "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "otherArrays")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-otherArrays PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-otherByteSwap "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "otherByteSwap")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-otherByteSwap PROPERTIES  LABELS "")
ADD_TEST(vtkCommonCoreCxx-otherStringArray "/home/cheen/Desktop/410/VTK-build/bin/vtkCommonCoreCxxTests" "otherStringArray")
SET_TESTS_PROPERTIES(vtkCommonCoreCxx-otherStringArray PROPERTIES  LABELS "")
