# CMake generated Testfile for 
# Source directory: /home/cheen/Desktop/410/VTK/Infovis/Core/Testing/Cxx
# Build directory: /home/cheen/Desktop/410/VTK-build/Infovis/Core/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkInfovisCoreCxx-TestStringToNumeric "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestStringToNumeric" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestStringToNumeric PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestMergeTables "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestMergeTables" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestMergeTables PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-ArrayDotProductSimilarity "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "ArrayDotProductSimilarity" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-ArrayDotProductSimilarity PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-ArraySparseArrayToTable "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "ArraySparseArrayToTable" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-ArraySparseArrayToTable PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-ArrayTableToSparseArray "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "ArrayTableToSparseArray" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-ArrayTableToSparseArray PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-ArrayToTable "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "ArrayToTable" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-ArrayToTable PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-ArrayTransposeMatrix "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "ArrayTransposeMatrix" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-ArrayTransposeMatrix PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestArrayNorm "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestArrayNorm" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestArrayNorm PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestCollapseVerticesByArray "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestCollapseVerticesByArray" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestCollapseVerticesByArray PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestDataObjectToTable "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestDataObjectToTable" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestDataObjectToTable PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestExtractSelectedTree "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestExtractSelectedTree" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestExtractSelectedTree PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestExtractSelectedGraph "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestExtractSelectedGraph" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestExtractSelectedGraph PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestGraphAlgorithms "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestGraphAlgorithms" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Infovis/Core/Testing/Data/Baseline/TestGraphAlgorithms.png")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestGraphAlgorithms PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestMergeGraphs "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestMergeGraphs" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestMergeGraphs PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestPruneTreeFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestPruneTreeFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Infovis/Core/Testing/Data/Baseline/TestPruneTreeFilter.png")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestPruneTreeFilter PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestRandomGraphSource "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestRandomGraphSource" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestRandomGraphSource PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestReduceTable "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestReduceTable" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestReduceTable PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestRemoveIsolatedVertices "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestRemoveIsolatedVertices" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestRemoveIsolatedVertices PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestStreamGraph "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestStreamGraph" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestStreamGraph PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestTableToArray "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestTableToArray" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestTableToArray PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestThresholdTable "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestThresholdTable" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestThresholdTable PROPERTIES  LABELS "")
ADD_TEST(vtkInfovisCoreCxx-TestTreeDifferenceFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkInfovisCoreCxxTests" "TestTreeDifferenceFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInfovisCoreCxx-TestTreeDifferenceFilter PROPERTIES  LABELS "")
