# CMake generated Testfile for 
# Source directory: /home/cheen/Desktop/410/VTK/Filters/Core/Testing/Cxx
# Build directory: /home/cheen/Desktop/410/VTK-build/Filters/Core/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkFiltersCoreCxx-TestAppendFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestAppendFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestAppendFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestAppendPolyData "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestAppendPolyData" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestAppendPolyData PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestAppendSelection "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestAppendSelection" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestAppendSelection PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestArrayCalculator "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestArrayCalculator" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestArrayCalculator PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestAssignAttribute "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestAssignAttribute" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestAssignAttribute PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestCellDataToPointData "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestCellDataToPointData" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestCellDataToPointData PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestCenterOfMass "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestCenterOfMass" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestCenterOfMass PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestCleanPolyData "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestCleanPolyData" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestCleanPolyData PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestClipPolyData "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestClipPolyData" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestClipPolyData PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestConnectivityFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestConnectivityFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestConnectivityFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestCutter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestCutter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestCutter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestDecimatePolylineFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestDecimatePolylineFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/Core/Testing/Data/Baseline/TestDecimatePolylineFilter.png")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestDecimatePolylineFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestDecimatePro "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestDecimatePro" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestDecimatePro PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestDelaunay2D "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestDelaunay2D" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/Core/Testing/Data/Baseline/TestDelaunay2D.png")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestDelaunay2D PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestDelaunay3D "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestDelaunay3D" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestDelaunay3D PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestExecutionTimer "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestExecutionTimer" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestExecutionTimer PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestFeatureEdges "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestFeatureEdges" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestFeatureEdges PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestFlyingEdges "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestFlyingEdges" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/Core/Testing/Data/Baseline/TestFlyingEdges.png")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestFlyingEdges PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestGlyph3D "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestGlyph3D" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/Core/Testing/Data/Baseline/TestGlyph3D.png")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestGlyph3D PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestHedgeHog "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestHedgeHog" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestHedgeHog PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestImplicitPolyDataDistance "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestImplicitPolyDataDistance" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/Core/Testing/Data/Baseline/TestImplicitPolyDataDistance.png")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestImplicitPolyDataDistance PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestMaskPoints "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestMaskPoints" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestMaskPoints PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestNamedComponents "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestNamedComponents" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestNamedComponents PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestPolyDataConnectivityFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestPolyDataConnectivityFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestPolyDataConnectivityFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestProbeFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestProbeFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestProbeFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestProbeFilterImageInput "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestProbeFilterImageInput" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Filters/Core/Testing/Data/Baseline/TestProbeFilterImageInput.png")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestProbeFilterImageInput PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestSmoothPolyDataFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestSmoothPolyDataFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestSmoothPolyDataFilter PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestSMPPipelineContour "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestSMPPipelineContour" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestSMPPipelineContour PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestStripper "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestStripper" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestStripper PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestStructuredGridAppend "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestStructuredGridAppend" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestStructuredGridAppend PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestThreshold "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestThreshold" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestThreshold PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestThresholdPoints "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestThresholdPoints" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestThresholdPoints PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestTransposeTable "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestTransposeTable" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestTransposeTable PROPERTIES  LABELS "")
ADD_TEST(vtkFiltersCoreCxx-TestTubeFilter "/home/cheen/Desktop/410/VTK-build/bin/vtkFiltersCoreCxxTests" "TestTubeFilter" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkFiltersCoreCxx-TestTubeFilter PROPERTIES  LABELS "")
