# CMake generated Testfile for 
# Source directory: /home/cheen/Desktop/410/VTK/Domains/Chemistry/Testing/Cxx
# Build directory: /home/cheen/Desktop/410/VTK-build/Domains/Chemistry/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkDomainsChemistryCxx-TestBallAndStick "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestBallAndStick" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestBallAndStick.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestBallAndStick PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestPDBBallAndStick "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestPDBBallAndStick" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestPDBBallAndStick.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestPDBBallAndStick PROPERTIES  LABELS "" RUN_SERIAL "ON" TIMEOUT "360")
ADD_TEST(vtkDomainsChemistryCxx-TestBondColorModeDiscreteByAtom "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestBondColorModeDiscreteByAtom" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestBondColorModeDiscreteByAtom.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestBondColorModeDiscreteByAtom PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestBondColorModeSingleColor "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestBondColorModeSingleColor" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestBondColorModeSingleColor.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestBondColorModeSingleColor PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestCompositeRender "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestCompositeRender" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestCompositeRender.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestCompositeRender PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestFastRender "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestFastRender" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestFastRender.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestFastRender PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestLiquoriceSticks "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestLiquoriceSticks" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestLiquoriceSticks.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestLiquoriceSticks PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestMolecule "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestMolecule" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMolecule PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestMoleculeSelection "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestMoleculeSelection" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMoleculeSelection PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestMoleculeMapperPropertyUpdate "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestMoleculeMapperPropertyUpdate" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestMoleculeMapperPropertyUpdate.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMoleculeMapperPropertyUpdate PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestMultiCylinderOn "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestMultiCylinderOn" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestMultiCylinderOn.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMultiCylinderOn PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestMultiCylinderOff "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestMultiCylinderOff" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestMultiCylinderOff.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMultiCylinderOff PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestPeriodicTable "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestPeriodicTable" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestPeriodicTable PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestProgrammableElectronicData "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestProgrammableElectronicData" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestProgrammableElectronicData PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestProteinRibbon "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestProteinRibbon" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestProteinRibbon.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestProteinRibbon PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestSimpleBondPerceiver "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestSimpleBondPerceiver" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestSimpleBondPerceiver PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestVDWSpheres "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestVDWSpheres" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestVDWSpheres.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestVDWSpheres PROPERTIES  LABELS "")
ADD_TEST(vtkDomainsChemistryCxx-TestCMLMoleculeReader "/home/cheen/Desktop/410/VTK-build/bin/vtkDomainsChemistryCxxTests" "TestCMLMoleculeReader" "-D" "/home/cheen/Desktop/410/VTK-build/ExternalData//Testing" "-T" "/home/cheen/Desktop/410/VTK-build/Testing/Temporary" "-V" "/home/cheen/Desktop/410/VTK-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestCMLMoleculeReader.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestCMLMoleculeReader PROPERTIES  LABELS "")
